---
title: "Thermodynamics"
description: |
  A short description of the post.
author:
  - name: Valerio Gherardi
    url: https://vgherard.github.io
date: 2024-06-07
output:
  distill::distill_article:
    self_contained: false
bibliography: biblio.bib
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Macroscopic systems, with a number constituents of the order of the Avogadro's 
number, are expected to follow the laws of Thermodynamics. In thermodynamics,
the interest is placed on the energy exchanges between macroscopic systems, 
which can always be described in terms of a few thermodynamic coordinates.

## Operative concepts

The following concepts are taken as given in the formulation of thermodynamics.

* **System.** The part of the universe that is the focus of our thermodynamic 
description. The state of a system is characterized by its macroscopic 
coordinates, the specification of which forms part of the experimental input to 
the thermodynamic description. 
* **Surroundings.** The part of the universe that interacts (*i.e.* exchanges 
energy) with the system. The characterization of the surroundings may also 
include the specification of some macroscopic coordinates (*e.g.* external 
pressure, force fields, temperature of thermal reservoirs...).
* **Work.** That fraction of energy exchanged by a system during a thermodynamic 
process, which *could* be produced by a change in the potential energy of 
some macroscopic object in the surroundings of the system^[The usage of the word
"could" is crucial here, since work is in general not always accompanied by a 
change in the potential energy of a body. Consider, for instance, the adiabatic 
expansion of a gas enclosed in a piston against the atmospheric pressure: the 
external force acting on the piston clearly does not come from a potential. What 
is true is that the same expansion could be realized in equivalent experimental
conditions in which the surroundings of the system (the atmosphere) are replaced
by some mechanical device that can perform work on the system by raising or
lowering a weight, as in the operative definition given next.]. In order to 
operationalize the notion of work, we assume 
that for any thermodynamic transformation there exist equivalent experimental 
conditions, under which the system passes through the same sequence of 
intermediate configurations connecting the initial and final states, and under 
which the performance of work is entirely attributed to the raising or lowering 
of a weight in a gravitational field^[Literally implementing this operative 
definition can be ridiculously cumbersome at some of the scales at which 
thermodynamics is usually assumed to apply, such as the particle scale of 
fluid-dynamics, or the astronomical scale of black holes.]. From the point of 
view of pure thermodynamics, the quantitative expression of work in any given
circumstance should be considered as an external input to the general theory, 
which may come either from direct measurement or from more detailed theories 
(*e.g.* mechanics, electromagnetism), always in accordance with the above 
operative definition.

## Laws of thermodynamics

### First law

> There exist experimental conditions, called *"thermal insulation"*, under 
which the work performed along a certain transformation depends only on the 
initial and final states of the system.

Here and below, the wording "adiabatic" will always refer to thermal insulation.

The operative definitions of *internal energy* and *heat* make use, in addition
to the First Law, of the following additional postulate, sometimes referred
to as the "Comparison Principle" [@LY1]:

> For any two states of a thermodynamic system, there exists an adiabatic 
process that features one of the two states as the initial, and the other as the
final state.

We can then define internal energy as the work required to bring a system
to a given state from a reference zero-energy state, in adiabatic conditions. 
Once internal energy is defined, we define the heat absorbed during a process as 
the difference between the internal energy change and the work performed on the
system.

All these results can be conveniently summarized by the equation:

$$
\Delta U = W+Q.(\#eq:FirstLaw).
$$


### Transitivity of thermal equilibrium ("Zero-th" Law)

Using the concepts introduced through to the First Law, especially those of
energy (in the thermodynamic sense of "internal energy") and heat, we may now 
state a principle, sometimes called the "Zero-th" Law[^zeroth], that 
characterizes *thermal equilibrium* as a transitive relation.

Two systems are said to be in *thermal contact* if they may exchange energy in 
the form of heat. When two systems, which are individually in equilibrium, are 
brought into thermal contact, they will generally undergo a series 
of changes, until reaching a new equilibrium state. At this point, we may say 
that the systems are in *thermal equilibrium*.

It is an empirical fact that thermal equilibrium is a transitive relation: 

> If two systems are in thermal equilibrium with a third system, they are also 
in thermal equilibrium with each other. 

If we take, as a probe for thermal equilibrium, a system which is essentially 
one-dimensional, such as an ideal gas held at a standard pressure, we can then 
conclude that thermal equilibrium can be characterized by a single number, an 
*empirical temperature*. The temperature of a system would be measured by the 
volume reached by our ideal gas probe once put in thermal contact with such 
system.

[^zeroth]: This principle is sometimes called the "Zero-th" Law of 
	Thermodynamics, because it is essential to the definition of temperature, 
	whose concept is taken for granted throughout the usual expositions of 
	Thermodynamics. In our formulation, the First Law precedes this principle 
	from a logical point of view.

### Second law

There's an important philosophical difference between the first and second law:
while both principles are understood as emergent laws of macroscopic systems,
the first law can be entirely interpreted in terms of a microscopic notion of
energy conservation, whereas there is no similar interpretation of the second 
law to our current knowledge.
