---
title: "Thermodynamic Potentials"
description: |
  A short description of the post.
author:
  - name: Valerio Gherardi
    url: https://vgherard.github.io
date: 2024-02-27
output:
  distill::distill_article:
    self_contained: false
draft: true
---


### Gibbs Free Energy

Consider a closed system whose thermodynamic coordinates include volume $V$ and pressure $p$. We define the Gibbs free energy as:

$$
G = U + pV-TS.
$$
The differential of $G$ is given by:

$$
\text{d}G = \text dU+p\,\text{d}V -T\,\text dS+V\,\text dp-S\text dT.
$$
Denoting by:

$$
\delta W = \text d U - T\,\text d S
$$

the work done on the system in a reversible transformation, we have:

$$
\text{d}G = \delta W+p\,\text{d}V+V\,\text dp-S\text dT.
$$
If $\delta W = -p \,\text d V$, this reduces to

$$
\text{d}G = V\,\text dp-S\text dT
$$

in a reversible transformation. Therefore $\text{d} G = 0$ is a necessary condition for thermodynamic equilibrium at constant pressure and temperature. 

The key observation here is that the derivation is not restricted by any means to simple hydrostatic systems (*i.e.* systems described in terms of volume and pressure *only*). The only condition for the validity of Eq. XXX is that the total external work $\delta W = -p \,\text d V$. 

The canonical example here is a pure substance with two phases in thermodynamic equilibrium, such as water vapor in equilibrium with liquid water. Letting $m_i,\,p_i,\,V_i$, with $i = 1,\,2$ denote the masses, pressures and volumes of the two distinct phases, we have three *a priori* constraints on these quantities, namely:

- Conservation of mass $m_1 + m_2 = m$,
- Mechanical equilibrium $p_1 = p_2 = p$,
- Thermal equilibrium $T_1 = T_2 = T$,

that allow us to reduce the number of variables from six to three, which we can choose to be $p$, $T$ and $m_2$. A fourth constraint is provided by the stationarity of Gibbs potential, which yields a relation between pressure and temperature at the phase transition. 

Let us introduce the specific quantities:

$$
\begin{split}
V_i(p,T,m_i) &= m_iv_i(p,T), \\
U_i(p,T,m_i) &= m_iu_i(p,T),\\
S_i(p,T,m_i) &= m_is_i(p,T),
\end{split}
$$
The Gibbs potential of each phase can thus be written as:

$$
G_i = m_i(u_i+pv_i-Ts_i)=m_ig_i(p,T)
$$
and the total Gibbs potential is $G = m_1g_1 + m_2g_2$. Thermodynamic equilibrium requires $\frac{\partial G}{\partial m_2} = 0$, that is 

$$
g_1(p,T) = g_2(p,T)
$$
which means that $p$ and $T$ are not independent at the phase transition. If we solve the equilibrium condition for $p=p(T)$, and plug this in into $u_i = u_i(p,T)$ etc., we see that also thermodynamic specific quantities are functions of $T$ only.

If we take the differential of the previous equation, noticing that:

$$
\text{d}g _i =-s_i\text{d}T+v_i\text{d}P
$$
we obtain

$$
\frac{\text d P}{\text d T} = \dfrac{s_2 - s_1}{v_2 - v_1}
$$
Denoting by $\lambda \equiv T(s_2 - s_1)$ the latent heat of the phase transition, we have:

$$
\frac{\text d P}{\text d T} = \dfrac{\lambda}{T(v_2 - v_1)}
$$
