# See https://quarto.org/docs/reference/projects/websites.htm

project:
  type: website
  output-dir: docs

website:
  title: "vgherard"
  description: "Valerio Gherardi's Personal Website"
  #announcement	https://quarto.org/docs/reference/projects/websites.html#announcement
  site-url: "https://vgherard.github.io"
  repo-url: "https://github.com/vgherard/vgherard.github.io/"
  #favicon:
  #image: Default site thumbnail image for twitter /open-graph
	#image-alt: Default site thumbnail image alt text for twitter /open-graph
  #google-analytics:

  draft-mode: gone

  comments:
    giscus:
      repo: "vgherard/vgherard.github.io"
      repo-id: "MDEwOlJlcG9zaXRvcnkzODI2MzU4NTQ="
      category: "Comments"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - notebooks.qmd
      - software.qmd
      - scientific_publications.qmd
      - files.qmd
      - about.qmd
      - icon: rss
        href: index.xml
    right:
      - icon: github
        href: https://github.com/vgherard
      - icon: linkedin
        href: https://www.linkedin.com/in/vgherard/
      - icon: twitter
        href: https://twitter.com/ValerioGherardi
      - icon: envelope
        href: mailto:vgherard840@gmail.com
      - text: CV
        href: https://raw.githubusercontent.com/vgherard/cv/master/cv/cv.pdf
      - text: "Other links"
        menu:
          - text: "vgherard @ r-bloggers"
            href: https://www.r-bloggers.com/author/vgherard/
          # - text: "vgherard @ datascience+"
          #   href: https://datascienceplus.com/author/vgherard/
          - text: "vgherard @ StackExchange"
            href: https://stackexchange.com/users/2261006/pppqqq
          - text: "vgherard @ iNSPIRE HEP"
            href: https://inspirehep.net/authors/1728353?ui-citation-summary=true
          # - text: "vgherard @ exercism"
          #   href: https://exercism.io/profiles/vgherard
          - text: "vgherard @ lichess.org"
            href: https://lichess.org/@/vgherard
          # - text: "vgherard @ Chess.com"
          #   href: https://www.chess.com/member/vgherard
          - text: "vgherard @ FIDE"
            href: https://ratings.fide.com/profile/94715360

  margin-header: _subscribe.html

  google-analytics: "G-BM2Y0430QE"

  cookie-consent:
    style: simple
    type: express
    palette: light
    lang: en
    cookies_policy: url

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
