---
title: "Statements of the Second Law of Thermodynamics"
description: |
  Close-up on the equivalence between Kelvin's/Clausius' postulates and 
  Clausius' *theorem*.
author:
  - name: Valerio Gherardi
    url: https://vgherard.github.io
date: 2024-06-01
output:
  distill::distill_article:
    self_contained: false
bibliography: biblio.bib
categories: 
  - Thermodynamics
  - Physics
draft: false
---

The Second Law of Thermodynamics is commonly stated in the forms of Kelvin's 
and Clausius' postulates. These can be enunciated in the following 
way [@dittman2021heat] [^fermi]:

> **Kelvin's Postulate.** It is impossible to construct an engine that, 
operating in a cycle, will produce no effect other than the extraction of heat 
from a reservoir and the performance of an equivalent amount of work.

> **Clausius' Postulate.** It is impossible to construct a refrigerator that, 
operating in a cycle, will produce no effect other than the transfer of heat 
from a lower-temperature reservoir to a higher temperature reservoir.

Either formulation is equivalent to the other and leads to the fundamental 
*Clausius' theorem*. This asserts the existence of a universal state function
$T$, the *absolute temperature*, defined for any thermodynamic system, that 
satisfies the *Clausius inequality*. Concretely, if a system undergoes a cyclic 
process, during which it absorbs quantities $\Delta Q _i$ of energy in the form 
of heat from reservoirs at absolute temperatures $T_i$, the inequality:

$$
\sum _i\frac{\Delta Q_i}{T_i} \leq 0 (\#eq:ClausiusTheorem)
$$
always holds.

The derivation of Eq. \@ref(eq:ClausiusTheorem) from Kelvin's and Clausius' 
postulates, a clever argument that employs ideal Carnot engines, is standard 
textbook material; see for example [@fermi1956thermodynamics]. On the other 
hand, I've never seen the converse being stressed, that is, that Clausius 
theorem allows one to recover versions of Kelvin's and Clausius' postulates. 
Here are two (fairly obvious) arguments in this direction.

[^fermi]: We may compare these with the corresponding formulations given in 
	Enrico Fermi's famous book [@fermi1956thermodynamics]. For instance, Kelvin's 
	postulate reads: *"A transformation whose only final result is to transform 
	into work heat extracted from a source which is at the same temperature 
	throughout is impossible."*. Even though I'm a big fan of Fermi's book, I find 
	the more modern formulations given in [@dittman2021heat] clearer.

Consider a cyclic process of a thermodynamic system during which a quantity 
$\Delta Q$ of heat is absorbed from a reservoir at constant temperature $T_0$. 
Equation \@ref(eq:ClausiusTheorem) applied to this special process implies:

$$
\Delta Q\leq 0.(\#eq:KelvinProof1)
$$
The fact that $\Delta Q\leq 0$ means that the heat reservoir can only absorb
energy during a cycle, which must be supplied by performing a positive 
work on the system. This is the content of Kelvin's postulate.

Similarly, if the system performs a cycle exchanging amounts of heat 
$\Delta Q_1$ and $\Delta Q_2$ with two heat sources at temperatures $T_1$ and 
$T_2$ respectively, \@ref(eq:ClausiusTheorem) implies:

$$
\frac{\Delta Q_1}{T_1}+\frac{\Delta Q_2}{T_2}\leq 0(\#eq:ClausiusProof1)
$$
But $\Delta Q_1 + \Delta Q_2 = \Delta Q =-\Delta W$, the external work performed 
on the system during a cycle. Hence:

$$
(\frac{1}{T_1}-\frac{1}{T_2})\Delta Q_1\leq \frac{\Delta W}{T_2}.(\#eq:ClausiusProof2)
$$
Therefore, $\Delta Q_1 \geq 0$ with $T_1 < T_2$ requires $\Delta W \geq 0$. 
In other words, in order to perform a cycle in which a positive amount of heat 
is transferred from a low-temperature reservoir to a high-temperature one, we
must necessarily perform some positive work[^refrigerator]. This is the content 
of Clausius' postulate.

[^refrigerator]: In fact, Eq. \@ref(eq:ClausiusProof2) tells us a bit more than
	Clausius postulate, since it gives the maximum theoretical efficiency of a 
	refrigerator operating between temperatures $T_1 < T_2$:
	$$
	\frac{\Delta Q_1}{\Delta W} \leq \frac{T_1}{T_2-T_1}
	$$

A subtle point that may require some elucidation is that, in the usual logical
exposition of Thermodynamics, the temperature to which Kelvin's and Clausius' 
postulates make reference is the *empirical* temperature, call it $\theta$. This 
is the "quantity measured by a thermometer" [@fermi1956thermodynamics], and is 
logically distinct from the absolute temperature $T$, whose existence is a 
consequence of the second law. What we actually proved here are versions of 
Kelvin's and Clausius' postulates 
*formulated in terms of the absolute temperature*, $T$. 

Now, if we take Kelvin's or Clausius' postulate (formulated in terms of 
$\theta$) as our logical starting point, we can actually prove that $T$ is an 
increasing function of $\theta$, in which case there is no point in specifying 
which temperature the postulates refer to. However, if our starting point is  
Clausius' Theorem, there is no *a priori* logical reason for a relation between 
$T$ and $\theta$, which should be considered as an additional assumption.

---

Even though this goes a bit beyond the original scope of the post, I'd like to 
show here how \@ref(eq:ClausiusTheorem) leads the existence of another state 
function, the *entropy* $S$, which satisfies a generalized version of \@ref(eq:ClausiusTheorem), namely:

$$
\sum _i\frac{\Delta Q_i}{T_i} \leq \Delta S(\#eq:ClausiusTheoremEntropy)
$$

where quantities have the same meaning as in Eq. \@ref(eq:ClausiusTheorem), but
the process is not necessarily cyclic. One can additionally show that the 
differential of $S$ is given by:

$$
\text dS = \frac{\delta Q _R}{T}(\#eq:EntropyDifferential),
$$

where $\delta Q_R = \text d U + \delta W_R$ is the differential heat absorbed 
by the system in a reversible process, and $T$ is the system's temperature.

We start by observing that, for a reversible process, equality must hold in Eq.
\@ref(eq:ClausiusTheorem). This is so because, for a reversible cycle, the 
inverse cycle, in which the system absorbs amounts $-\Delta Q_i$ of heat 
at temperatures $T_i$, must also be possible. Altogether, the Clausius 
inequalities for the direct and inverse cycles thus imply:

$$
\sum _i\frac{\Delta Q_i}{T_i} = 0\quad \text{(reversible process)}(\#eq:ClausiusTheoremRev).
$$

Imagining an ideal cyclic process, in which the system exchanges infinitesimal 
amounts of heat $\delta Q(T')$ with a continuous distribution of sources at 
temperatures $T'$, we should replace the sum in Eq. \@ref(eq:ClausiusTheoremRev) 
with an integral:

$$
\intop \frac{\delta Q(T')}{T'} = 0 \quad\text{(reversible process)}(\#eq:ClausiusTheoremRevInt)
$$
We now fix a reference state $\sigma _0$ of our system, and define for any other
state $\sigma$:

$$
S(\sigma;\sigma _0) = \intop _{\sigma_0}^\sigma \frac{\delta Q(T')}{T'}(\#eq:EntropyDef)
$$
where the integral is taken along *any* reversible path that connects 
$\sigma _0$ and $\sigma$, and $\delta Q(T')$ is the amount of heat exchanged 
at temperature $T'$ along this representative process. The fact that the 
integral in \@ref(eq:EntropyDef) depends only upon the final states $\sigma _0$
and $\sigma$ is guaranteed by \@ref(eq:ClausiusTheoremRevInt).

By construction, we see that Eq. \@ref(eq:EntropyDifferential) must hold 
with $T$ being the temperature of a source that, if placed in thermal contact 
with the system, can produce a reversible exchange of heat. It remains to be 
shown that this temperature is nothing but the temperature of the system 
itself. Consider a reversible process in which two systems at temperatures 
$T_1$ and $T_2$ exchange an (infinitesimal) amount of heat. From what we have 
just said:

$$
\text d S_1 = \frac{\delta Q_1}{T_2},\quad \text d S_2 = \frac{\delta Q _2}{T_1},(\#eq:EntropyDifferentialsSwitched)
$$
where $\delta Q_i$ is the heat absorbed by system $i$, and $\text d S_i$ is its
corresponding entropy change. However, since the composite system is thermally 
insulated, we must have $\delta Q_1 + \delta Q_2=0$ and 
$\text d S_1 + \text d S_2 = 0$[^additive]. Eq. 
\@ref(eq:EntropyDifferentialsSwitched) then implies that, if the process is 
reversible, we must necessarily have $T_1 = T_2$. This completes the proof of \@ref(eq:EntropyDifferential).

[^additive]: The additivity of entropy is a consequence of the additivity of 
heat, which in turn would require a dedicate discussion. Such a requirement
boils down to the additivity of external work, which holds generally if the 
interaction energies of the systems being composed are negligible. This is 
always assumed (more or less explicitly) whenever discussing the interaction of
a system with a heat reservoir.
