---
title: Scientific Publications
page-layout: full
format:
  html:
    toc: false
---

## Environmental Science (2024-present)

Since 2024 I have worked in **Limnology** and **Ecotoxicology** through the [ERAHUMED project](https://www.erahumed.com/), where I co-developed the decision-support models and led software development. The work is currently ongoing.

#### Selected articles

-   [Thinking big! Landscape-scale evaluation of pesticide pollution and ecological risks in a protected mediterranean wetland](https://doi.org/10.1016/j.envpol.2025.126918) - covered by national and international media, *e.g.* [EuropaPress](https://www.europapress.es/comunitat-valenciana/noticia-estudio-uv-revela-lago-lalbufera-recibe-15-toneladas-pesticidas-ano-20250916103148.html), [ElDiario](https://www.eldiario.es/sociedad/albufera-valencia-recibe-1-5-toneladas-pesticidas-ano-estudio_1_12606096.html).

## Particle Physics (2017-2022)

My research in Particle Physics (2017-2022) overlapped with my PhD studies, focusing on **Non-perturbative methods in Quantum Field Theory** and **Beyond Standard Model phenomenology**. A full list of publications is available on [my iNSPIRE HEP author page](https://inspirehep.net/authors/1728353?ui-citation-summary=true). My PhD thesis can be accessed [on arXiv](https://arxiv.org/abs/2111.00285).

#### Selected articles

-   [Matching scalar leptoquarks to the SMEFT at one loop](https://arxiv.org/abs/2003.12525)
-   [Modular invariant dynamics and fermion mass hierarchies around $\tau = i$](https://arxiv.org/abs/2101.08718)
-   [Solving the Bethe-Salpeter Equation in Minkowski Space for a Fermion-Scalar system](https://arxiv.org/abs/1907.03079)

## Other Contributions

This section highlights occasional research work beyond my core areas.

#### Selected articles

-   [Grammar as a Behavioral Biometric: Using Cognitively Motivated Grammar Models for Authorship Verification](https://arxiv.org/abs/2403.08462) (preprint; under review).
