---
title: "\"Annual adult survival rates for four sympatric breeding swallow species\" by Imlay et al."
description: |
  An obscure mark-recapture data analysis.
date: 2024-04-25
bibliography: biblio.bib
categories: 
  - Comment on...
  - Population Dynamics
  - Biology
  - Statistics
draft: true
---

[@imlay2022annual]. From the paper's abstract:

> Swallow (Family: Hirundinidae) populations in the Canadian Maritimes have declined since the 1980s. Using mark–recapture data from 2012 to 2019, we determined apparent annual adult survival rates for Barn (Hirundo rustica Linnaeus, 1758), Tree (Tachycineta bicolor (Vieillot, 1808)), Bank (Riparia riparia (Linnaeus, 1758)), and Cliff (Petrochelidon pyrrhonota (Vieillot, 1817)) swallows. For two data-rich species (Barn and Tree swallows), we modelled the relationships between survival and weather (cold snaps, precipitation, temperature, and wind speed), climate (El Niño–Southern Oscillation (ENSO) and North Atlantic Oscillation (NAO)), Enhanced Vegetation Index (EVI) as a measure of primary productivity during the winter, number of active nests as a measure of site quality, and the Breeding Bird Survey (BBS) annual population index as density-dependent processes. Survival rates for all four species were typically higher (Barn and Tree) or similar to (Cliff and Bank) of estimates from populations that have not undergone severe, long-term declines. Across weather and climate variables, conditions that are typically favourable for high insect availability (e.g., higher precipitation, warmer temperatures, and lower wind speeds) resulted in higher survival. For female Barn and Tree swallows, survival was higher when EVI was lower, and for Barn Swallows, survival was also higher when the BBS index was higher. Collectively our results demonstrate that conditions throughout the annual cycle affect survival, and the relationships with weather and climate variables support the importance of high insect availability.

I'm reading this and similar references primarily because I want to get some intuition on the correlations between global scale climate variables such as ENSO and NAO, and bird survival on the other. Has any correlation been detected, how strong is it, which sectors of the population are most directly affected, *etc.etc.*.

Also, I'm looking for some good references of mark-recapture data analyses studying survival in relation to climate and weather, because I'm currently working on a very similar problem.

Unfortunately, this reference turned out to be of little help, because the statistical analysis leaves a lot to be desired - or is at least poorly explained.

The first, and in my opinion biggest problem, is the unconditional assumption of the Cormack-Jolly-Seber (CJS) model. Such a model is assumed to hold separately for each population of a given sex and species. Now, how did the authors assess whether this was a reasonable model for the data at hand? Some specific questions:

-   Is there any important age dependence in survival and recapture rates? The fact that the study is restricted to adults does not justify ignoring this issue (for instance, there may be important differences in survival due to senescence).

-   Is there any trap-dependence in recapture rates? By "trap-dependence" we refer to the fact that recapture probability of an individual may depend on whether it was captured or not at the previous capture occasion. This is another common violation of CJS assumptions.

-   Is there significant overdispersion? If so, this could hint to other violations of CJS assumptions. Independence of capture histories, just to provide one example.

-   Are the linearity (on the logit scale) assumptions concerning the dependence of survival rates from environmental covariates satisfied?

A second issue concerns model selection. Apparently, the only selection made by the authors is an "unsupervised" variable selection - with no reference to capture histories. Everything is boiling inside the pot, irrespective of whether the added variables are actually useful for the model's fit or not. Even though the authors may be realistically interested in estimating all the effects included in the model, it seems a bit unlikely that all such effects can be reliably estimated with the limited data at hand - as a rapid look to the final coefficient table confirms. The most likely result of adding all these contributions, negligible from the goodness of fit point of view, is to make the whole model estimation more noisy. Notice that such a behaviour is also at odds with the treatment of individual covariates such as age or trap-dependence, which are simply neglected, despite being possibly crucial for a good fit.

Finally, there are a few more so to say low-level mysterious points. First, it *looks* like the authors are performing a bayesian analysis (since they speak of credible intervals and MCMC for model estimation). If that's the case, what parameter priors are they using? How sensitive to this priors are the resulting posterior distributions? Second, the definition of the time-dependence of survival probabilities is not what I'm used to see when I hear "CJS" (what is that $\varepsilon$ noise term?).

I'm not saying that all the issues I mentioned here are necessarily crucial and easily diagnosed from the data available. However, ignoring them completely makes judging results which are *per se* very noisy (Table 2 of the reference) even harder. In my opinion, the authors could have likely come up with a more dependable model, simpler in terms of environmental covariates, and perhaps richer in terms of individual covariates, and could in any case have investigated a bit better if and how do their conclusions depend on untested modeling aspects.
