---
title: "Scraping the arXiv with R and GitHub Actions"
description: |
  How to automate arXiv metadata download using R and GitHub Actions (and a little bit of Python.)   
author:
    - name: vgherard
    url: https://vgherard.github.io
date: 2021-07-21
output:
  distill::distill_article:
    self_contained: false
    pandoc_args: ["--number-sections"]
categories:
  - R
draft: true

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Hi R-bloggers `r emo::ji("wave")` {.unnumbered}

Starting from today, all posts from this blog in the `R` category will also appear on [R-bloggers](https://www.r-bloggers.com/). I would like to thank Tal for aggregating my blog, and say "hi!" to all R-bloggers readers. I'm a particle physicist with a passion for R, Statistics and Machine Learning. If you want to find out something more about me, you can take a look at [my website](https://vgherard.github.io), and links therein.

# Introduction

In this post I explain how to setup a GitHub repository which automatically scrapes the [arXiv](https://arxiv.org) (downloading metadata such as author, category, title, abstract, etc.) using:

- [R](https://www.r-project.org/)
- [GitHub Actions](https://github.com/features/actions)
- A few extra dependencies to be detailed below.

I will take as an example my own repository [hepscrape](https://github.com/vgherard/hepscrape/), which holds a dataset of records from the `hep-ph` arXiv category that is updated on a daily basis. Each night, the repository:

1. Checks for new submissions on arXiv.
1. Aggregates the newly found records with older ones already present in the dataset.
1. Performs/updates a simple analysis on the data (at the time of writing, it creates a word cloud, shown in the README, with popular terms from the last 100 submissions).

My main purpose with [hepscrape](https://github.com/vgherard/hepscrape/) was to create a dataset which I could use for personal fun, but of course you can setup your own workflow using the same techniques I outline in this post.

# Retrieving arXiv metadata

We will use the [arXiv public API](https://arxiv.org/help/api), which can be easily accessed from R with the CRAN package [aRxiv](https://CRAN.R-project.org/package=aRxiv).


