---
title: "Stochastic Processes"
description: |
  A short description of the post.
author:
  - name: Valerio Gherardi
    url: https://vgherard.github.io
date: 2024-02-11
output:
  distill::distill_article:
    self_contained: false
draft: true
---

Let $\left(\Omega, \mathcal E , P\right)$ be a probability space. A stochastic process on $P$ with index set $T$ is a collection $X=(X_t)_{t\in T}$ of random variables $X_t \colon \Omega \to \mathbb R^n$.

A stochastic process gives rise to a set of (Borel) probability measures on 
$\mathbb R ^n$ defined by:

$$
P_{t_1,\,t_2,\,\dots\,t_n}(B_1\times B_2 \times \cdots \times B_n) = \text{Pr}(X_{t_1}\in B_1,\,X_{t_2}\in B_2,\,\dots,\,X_{t_n}\in B_n)\qquad (t_i \in T)
$$
on products of Borel sets and extended by the Hahn-Kolmogorov theorem to $\mathcal B (\mathbb R ^n)$. These measures satisfy:

1. Permutation invariance:
$$
P_{t_{\pi(1)},\,t_{\pi(2)},\,\dots\,t_{\pi(n)}}(B_{\pi(1)}\times B_{\pi(2)} \times \cdots \times B_{\pi(n)})=P_{t_1,\,t_2,\,\dots\,t_n}(B_1\times B_2 \times \cdots \times B_n).
$$
for any permutation $\pi$ on $\{1,\,2,\,\dots,\,n\}$.

2. Projection invariance:
$$
P_{t_1,\,t_2,\,\dots\,t_n,\,t_{n+1}}(B_1\times B_2 \times \cdots \times B_n\times \mathbb R)=P_{t_1,\,t_2,\,\dots\,t_n}(B_1\times B_2 \times \cdots \times B_n).
$$
Conversely, it can be shown that any set of $T$-indexed measures satisfying these two properties are generated by a stochastic process $X$ on a probability space $\left(\Omega, \mathcal E,P\right)$. The constructive proof of this theorem defines the space of random outcomes $\Omega$ to be $\mathbb R ^T=\{\omega\colon T\to \mathbb R\}$, the set of real valued functions on $T$, and the associated stochastic process as:

$$
X_t(\omega) = \omega(t)
$$
The probability measure $P$ is defined on "cylinder" sets by:

$$
P(\{\omega\in \Omega \colon\, \omega(t_1) \in B_1,\,\omega(t_2) \in B_2,\,\dots,\,\omega(t_n) \in B_n\}) = P_{t_1,\,t_2,\,\dots\,t_n}(B_1\times B_2 \times \cdots \times B_n).
$$
Now suppose that a group $G$ acts freely and transitively on the index set $T$, so that for $t_0,\,t_1\in T$ there is a unique $g\in G$ such that 
$t_1 = g\cdot \,t_0$; if we fix $t_0\in T$, we can write $t = g(t)t_0$ for every
$t\in T$. Hence:

$$
X_t(\omega)=\omega(t)=\omega(g(t)t_0)=(g(t)^*\omega)(t_0)=X_{t_0}(g(t)^*\omega),
$$

which shows that $X_t$ can be thought as the composition of a single random
variable on $\Omega$ and a pullback operation from a group action on $T$.

Consider in particular the case $T = \mathbb Z$. Then $X$ is a discrete stochastic process, and elements of $\Omega$ are real valued sequences. The free transitive action corresponds to translations such as $(U_s \omega)_t=\omega_{s+t}$. In fact, we have $U_s = (U_1)^s\equiv U^s$, so that:

$$
X_t(\omega) = X_0(U^t\omega) 
$$
Similarly, if $T = \mathbb R ^d$, we have:

$$
X_t(\omega) = X_0(\theta _t ^*\omega)
$$

where $\theta _t ^*\omega(s)= \omega(s+t)$.

----

Stationarity: $P(U^t A) = P(A)$ for all $A$.


---

Ergodicity: 

Suppose that $X_t(\omega) \in A$ for all $t$. This means that $\omega(t) \in A$
for all $t\in T$. The set of sequences with such a restricted domain is 
invariant under translations, so ergodicity requires that its probability be 
$P=0$. Now:

$$
P = \text{Prob}(X_1 \in A) \text{Prob}(X_2 \in A \vert X_1 \in A)
$$



