---
title: "Thermodynamics"
date: 2024-07-31
bibliography: biblio.bib
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Miscellaneous notes about concepts of Thermodynamics.

## Systems

The system is the part of the universe that is the focus of our thermodynamic description. The state of a system is characterized by its macroscopic coordinates, the specification of which forms part of the experimental input to the thermodynamic description.

The system's surroundings is the part of the universe that interacts (that is exchanges energy) with the system. The characterization of the surroundings may also include the specification of some macroscopic coordinates (*e.g.* external pressure, force fields, temperature of thermal reservoirs...).

## Work

The notion of "work" in Thermodynamics generally refers that fraction of energy exchanged by a system during a thermodynamic process, which *could* be produced by a change in the potential energy of some macroscopic object interacting with the system. In order to operationalize this intuition, we may assume that for any thermodynamic process there exist equivalent experimental conditions, under which the system passes through the same sequence of intermediate configurations connecting the initial and final states, and under which the performance of work is entirely implemented by the raising or lowering of a weight in a gravitational field.

From the formal point of view, the quantitative expression of work in any given circumstance should be considered as an external input to the general theory. This may come either from direct measurement or from more detailed theories (*e.g.* mechanics, electromagnetism), always in accordance with the above operative definition.

It should be stressed that thermodynamics does not provide by itself any means to determine the "equivalent experimental conditions" referred to in the operative definition above, nor any guidance for calculating work from first principles. The ultimate test of whether a theoretical or empirical assessment of work is correct is the consistency of the resulting thermodynamic description for the system under consideration.

## Laws of thermodynamics

### First law

> There exist experimental conditions, called *"thermal insulation"*, under which the work performed along a certain transformation depends only on the initial and final states of the system.

Here and below, the wording "adiabatic" will always refer to thermal insulation.

The operative definitions of *internal energy* and *heat* make use, in addition to the First Law, of the following additional postulate, sometimes referred to as the "Comparison Principle" [@LY1]:

> For any two states of a thermodynamic system, there exists an adiabatic process that starts in one of the two states and ends in the other.

We can then define internal energy as the work required to bring a system to a given state from a reference zero-energy state, in adiabatic conditions. Once internal energy is defined, we define the heat absorbed during a process as the difference between the internal energy change and the work performed on the system. These definitions are conventionally summarized by the equation:

$$
\Delta U = W+Q.
$$ {#eq-first-law}

### Transitivity of thermal equilibrium ("Zero-th" Law)

Two systems are said to be in *thermal contact* if they may exchange energy in the form of heat. When two systems, which are individually in equilibrium, are brought into thermal contact, they will generally undergo a series of changes, until reaching a new equilibrium state. At this point, we may say that the systems are in *thermal equilibrium*.

It is an empirical fact that:

> If two systems are in thermal equilibrium with a third system, they are also in thermal equilibrium with each other.

If we take, as a probe for thermal equilibrium, a system which is essentially one-dimensional, such as an ideal gas held at a standard pressure, we can then conclude that thermal equilibrium can be characterized by a single number, an *empirical temperature*. The temperature of a system would be measured by the volume reached by our ideal gas probe once put in thermal contact with such system.

This principle is sometimes referred to as the "Zero-th" Law of Thermodynamics, because it is essential to the definition of temperature, whose concept is taken for granted throughout the usual expositions of Thermodynamics. In our formulation, the First Law precedes this principle from a logical point of view.
