on:
  push:
    branches: master
	 schedule:
    - cron: '59 23 * * *'
name: Render Code page

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages("distill")
          install.packages("jsonlite")
          install.packages("fontawesome")
        shell: Rscript {0}

      - name: Render Site
        run: Rscript -e 'rmarkdown::render("code.Rmd", encoding = "UTF-8")'
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
